version: "3.8"
services:

  guildpostgres:
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.region == ru"
    image: mirror.gcr.io/postgres:16.4-alpine
    networks:
      - my-custom-network
    restart: always
    environment:
      - POSTGRES_DB=guild-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg-data-guild:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5435:5432"

volumes:
  pg-data-guild:
    driver: local

networks:
  traefik_network:
    external: true
  my-custom-network:
    external: true