server:
  forward-headers-strategy: native
  port: ${SERVER_PORT:8081}
  jetty:
    max-http-response-header-size: 64KB
  servlet:
    context-path: /api
spring:
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
    serialization:
      write-dates-as-timestamps: false
  application:
    name: efs-server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  main:
    allow-circular-references: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
services:
  guild:
    url: ${FUEL_SERVER_URL:http://localhost:8080}
    timeOut: ${FUEL_SERVER_TIMEOUT:3000} #in millis
  auth:
    url: ${AUTH_SERVER_URL:https://auth.noxly.ru}
    timeOut: ${AUTH_SERVER_TIMEOUT:3000} #in millis
