server:
  forward-headers-strategy: native
  port: ${SERVER_PORT:8082}
  jetty:
    max-http-response-header-size: 64KB
  servlet:
    context-path: /api
spring:
  application:
    name: web-socket-server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jpa:
    openInView: true
    show-sql: false
    generateDdl: false
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    allow-circular-references: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
redis:
  host: ${REDIS_HOST:localhost}       # Адрес Redis-сервера
  port: ${REDIS_PORT:6380}
